{% set version = "3.9.3-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rwekajars
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RWekajars_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RWekajars/RWekajars_{{ version }}.tar.gz
  sha256: 16e6b019aab1646f89c5203f0d6fc1cb800129e5169b15aaef30fd6236f5da1a

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rjava >=0.6_3
  run:
    - r-base
    - r-rjava >=0.6_3

test:
  commands:
    - $R -e "library('RWekajars')"           # [not win]
    - "\"%R%\" -e \"library('RWekajars')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RWekajars
  license: GPL-2
  summary: External jars required for package 'RWeka'.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RWekajars
# Version: 3.9.3-1
# Title: R/Weka Interface Jars
# Authors@R: c(person("Kurt", "Hornik", role = c("aut", "cre"), email = "Kurt.Hornik@R-project.org", comment = c(ORCID = "0000-0003-4198-9911")), person("University of Waikato", role = c("ctb", "cph"), comment = "Weka Java library"))
# Description: External jars required for package 'RWeka'.
# Imports: rJava (>= 0.6-3)
# SystemRequirements: Java (>= 8)
# License: GPL-2
# NeedsCompilation: no
# Packaged: 2018-09-10 07:11:04 UTC; hornik
# Author: Kurt Hornik [aut, cre] (<https://orcid.org/0000-0003-4198-9911>), University of Waikato [ctb, cph] (Weka Java library)
# Maintainer: Kurt Hornik <Kurt.Hornik@R-project.org>
# Repository: CRAN
# Date/Publication: 2018-09-10 07:25:46 UTC
