travis:
  secure:
    BINSTAR_TOKEN: YgkDzLQBlyBDBTAi8NyDwsDLEe+jVjzryUBp5/V1OzXqO5id0GLE8TQtQ2EPTpr2QjHhUVNprQ9kkNT2GseZSR8eSwjIjczZYKMQ2kopuzGYAZlZLUmCF5p59ckEXjj54aJMUBSEUNURR0eyH2DOLwEjMNq7AWYgoyIQsrKvh1KN3qo+98zMpPbn5WY7HVhpl3BCJME3xXg7dEiP3WB4fRP623tNR/b2ZlcWVtlvaZS68j3cQIfrCZg2+jW3tgGdzRsV/YyZTUVKhcEaRP+CJwUF3sXSh1ll7BJ5wRkdV4iPc+3mCb8U0UMv3mD3yp1j4zPQFcarANVxX6SerRdnos9O1ox87rU0ZMRfhuY9KRDL2VtvgiLnUY9RrrQp0rDNdd7ZeUBaxo7d7zZLzTbH4mVfe8GrrP+tzbXnye87QFXJd5sW8J6F7H7eRySs36gyofEawcoi+XknWFxB913QqXx4/wbcVX/3rgoWXsOD7/pURNNAzmeJJ5NBo6bcczH/6I4DOSWz6iTNiEp+jdFQ4nAmbxNMlABZUYMX6CFuT4uyRmjY+Fdf2OkEI+5ybT59y6V3ZoUoaQxYGthOFcOAOVXcv10HfO01tdmkz09qSuUcP0pS9NjdgS3XISdbzQHyo5wwavS2HV3Y7HuxH1yP9hevVNQ73KxFPAH/pt6mP9c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
